[package]
name = "file"
version = "0.1.0"
authors = ["Joel Shepherd <joel@swivid.ink>"]
edition = "2018"

[dependencies]
gpgme = "0.9"
serde = { version = "1.0", features = ["derive"] }
ssh2 = "0.8"
structopt = "0.3"
tar = "0.4"
toml = "0.5"
url = "2.2"